services:
  redis:
    image: redis:latest
    container_name: user-service-redis
    ports:
      - "6379:6379"
    networks:
      - user-network

  user-service:
    image: user-service
    container_name: user-service
    ports:
      - "8082:8082"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - redis
    networks:
      - user-network

networks:
  user-network:
    driver: bridge