apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: asset-spy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: nastss6tx5/asset-spy-user-service:latest
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: user-service-config
            - secretRef:
                name: user-service-secret
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 192Mi
              cpu: 200m
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx192m -Xmx192m"
