apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: asset-spy
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30082
  type: NodePort
